API Endpoints of link:.[`pikne-zadania`]
========================================
Marcin Zepp <nircek-2103@protonmail.com>
v0.3, 2021-09-09: Revision 4
:issue: https://github.com/Pikne-Programy/pikne-zadania/issues/34[#34]
:stylesheet: main.css
:linkcss:
:docinfo1:
:icons: font
:toc:
:toclevels: 3

ifndef::env-github[]
++++
<div style="display:none;">
<ul class="styles">
<li class="current">Light</li>
<li>Dark</li>
</ul>
</div>
++++
endif::[]

NOTE: Discuss API v{revnumber} at {issue}.

== Throwing errors

If there is an error (`4xx` or `5xx` HTTP status code), the API will return either no content or the JSON object with an error message:

[source,json]
----
{
  "status": 500,
  "message": "<error message>"
}
----

The `"status"` property is a status code of the response.

== The most common status codes

* `200 OK`, when the request is succesful,
* `400 Bad Request`, when the request is invalid,
* `401 Unauthorized`, when the User must authenticate but the authentication failed or was not provided; +
  the unauthenticated will always get `401 Unauthorized` instead of `403 Forbidden`.
* `403 Forbidden`, when the User is not authorized to make a request (see "It can be used by" section),
* `404 Not Found`, when the requested resource does not exist,
* `500 Internal Server Error`, when there is a problem on the server-side.

IMPORTANT: The request will have a `403 Forbidden` status code instead of `404 Not Found` one when a resource is unavailable for the User to list (or it would be if it existed).

== Endpoints

=== Subject

==== `GET /api/subject/list` - list all available subjects [[GET_api_subject_list]]

.It can be used by
* anyone.

.Special status codes

.Request

[source,json]
----
----

.Response

[source,json]
----
{
  "subjects": ["fizyka", "_fizyka", "astronomia"]
}
----

.Notes

// subjects-:only-available
* There are only subjects available for the User.

==== `POST /api/subject/create` - create a new subject [[POST_api_subject_create]]

.It can be used by
* all teachers.

.Special status codes
* `409 Conflict` - the name (the `subject` property) is already taken.

.Request

[source,json]
----
{
  "subject": "fizyka",
  "assignees": [
    "1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755"
  ]
}
----

.Response

[source,json]
----
----

.Notes

// subject+:underscore-prefix
* Subjects that begins with the `_` character are private and not visible to unauthorized users.
// assignees+:empty-warning
* Only the Admin will be managing the subject if the `assignees` property equals `[]`.
// subject+:unique
* `subject` is a name and an id simultaneously.
It has to be unique.
// assignees+:def
* If the `assignees` property equals `null`, all teachers will be able to manage the subject.

==== `POST /api/subject/info` - read assignees of a subject [[POST_api_subject_info]]

.It can be used by
* all assignees of a subject,
* or all teachers if a subject's `assignees` equals `null`.

.Special status codes

.Request

[source,json]
----
{
  "subject": "fizyka"
}
----

.Response

[source,json]
----
{
  "assignees": [
    {
      "userId": "1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755",
      "name": "Smith"
    }
  ]
}
----

.Notes

// assignees-:def
* If the `assignees` property equals `null`, all teachers can modify the subject.

==== `POST /api/subject/permit` - update assignees of a subject [[POST_api_subject_permit]]

.It can be used by
* all assignees of a subject.

[sidebar]
QUESTION: should we permit all teachers to use this request if a subject's `assignees` equals `null`?
// add if so:
// or all teachers if a subject's `assignees` equals `null`.

.Special status codes

.Request

[source,json]
----
{
  "subject": "fizyka",
  "assignees": [
    "1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755"
  ]
}
----

.Response

[source,json]
----
----

.Notes

// assignees+:def
* If the `assignees` property equals `null`, all teachers will be able to manage the subject.

=== Problem managing

==== `POST /api/subject/problem/get` - render an exercise [[POST_api_subject_problem_get]]

.It can be used by
* anyone if a subject is public and an exercise is listed in a subject's hierarchy,
* all assignees of a subject.

.Special status codes

.Request

[source,json]
----
{
  "subject": "fizyka",
  "exerciseId": "pociagi-dwa",
  "seed": 0
}
----

.Response

[source,json]
----
{
  "type": "EqEx",
  "name": "Pociągi dwa 2",
  "done": 0.34,
  "problem": {
    "main": "Z miast \\(A\\) i \\(B\\) odległych o \\(d=300\\;\\mathrm{km}\\) wyruszają jednocześnie\ndwa pociągi z prędkościami \\(v_a= 50\\;\\mathrm{\\frac{km}{h}}\\) oraz \\(v_b=70\\;\\mathrm{\\frac{km}{h}}\\).\nW jakiej odległości \\(x\\) od miasta \\(A\\) spotkają się te pociągi?\nPo jakim czasie \\(t\\) się to stanie?",
    "img": ["1.png", "2.png"],
    "unknown": [
      ["x", "\\mathrm{km}"],
      ["t", "\\mathrm{s}"]
    ]
  },
  "correctAnswer": {
    "answers": [2.5, 125]
  }
}
----

.Notes

// seed+?:teacher|admin
* Only the Teacher and the Admin can use the `seed` property.
Otherwise, the database provides it.
// correctAnswer-:teacher|admin
* Only the Teacher and the Admin receive the `correctAnswer` property.
// done-:def
* The `done` property can be `null` or a number from 0 up to and including 1, see https://github.com/Pikne-Programy/pikne-zadania/issues/24#issuecomment-782939873[#24].
// problem-:ext-dependent
* The `problem` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.
// problem-:links2static
* The `problem` property can contain links to static content.
The User can access it via the <<GET_api_subject_static_.subject_.filename>> request.

==== `POST /api/subject/problem/update` - submit an answer & store it [[POST_api_subject_problem_update]]

// TODO: change name to submit in v0.4

.It can be used by
* anyone if a subject is public and an exercise is listed in a subject's hierarchy,
* all assignees of a subject.

.Special status codes

.Request

[source,json]
----
{
  "subject": "fizyka",
  "exerciseId": "pociagi-dwa",
  "answer": {
    "answers": [15.000000000000004, 13]
  }
}
----

.Response

[source,json]
----
{
  "info": [false, true]
}
----

.Notes

// info-:ext-dependent
* The `info` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.

=== Static files managing

==== `GET /api/subject/static/:subject/:filename` - get a static file [[GET_api_subject_static_.subject_.filename]]

.It can be used by
* anyone if a subject is public,
* all assignees of a subject.

.Special status codes

.Request

.Response

.Notes

// /static-:binary-data
* There should be binary data with an appropriate Content-type in the response.

==== `PUT /api/subject/static/:subject/:filename` - upload a static file [[PUT_api_subject_static_.subject_.filename]]

.It can be used by
* all assignees of a subject.

.Special status codes

.Request

.Response

.Notes

// /static+:multipart
* The request data should follow the `multipart/form-data` Content-type.

=== Hierarchy modification

==== `POST /api/subject/hierarchy/get` - read an exercise hierarchy of a subject [[POST_api_subject_hierarchy_get]]

.It can be used by
* anyone if a subject is public,
* all assignees of a subject.

.Special status codes

.Request

[source,json]
----
{
  "subject": "fizyka",
  "raw": false
}
----

.Response

[source,json]
----
[
  {
    "name": "",
    "children": [
      {
        "type": "EqEx",
        "name": "Kula 2",
        "children": "kula-2",
        "description": "TODO",
        "done": null
      }
    ]
  },
  {
    "name": "mechanika",
    "children": [
      {
        "name": "kinematyka",
        "children": [
          {
            "type": "EqEx",
            "name": "Pociągi dwa 2",
            "children": "pociagi-dwa",
            "description": "Z miast \\(A\\) i \\(B\\) odległych o \\(d= 300\\;\\mathrm{km}\\) wyruszają jednocześnie\ndwa pociągi z prędkościami \\(v_{a}= \\;\\mathrm{\\frac{km}{h}}\\) oraz \\(v_{b}= \\;\\mathrm{\\frac{km}{h}}\\).\nW jakiej odległości \\(x\\) od miasta \\(A\\) spotkają się te pociągi?\nPo jakim czasie \\(t\\) się to stanie?\n",
            "done": 0.34
          }
        ]
      }
    ]
  }
]
----

.Notes

// description-&done-?:raw=false
* If the `raw` property equals `false`, there is the `description` property and can be the optional `done` property if the User is authenticated.
// /hierarchy.subsubject:exs-not-listed
* If the `raw` property equals `false` and the User is authorized, there is a `{"name": "", children: [...]}` (sub-subject) object with all exercises not listed in the hierarchy.
// description-:ext-dependent
* The `description` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.
// done-:def
* The `done` property can be `null` or a number from 0 up to and including 1, see https://github.com/Pikne-Programy/pikne-zadania/issues/24#issuecomment-782939873[#24].

==== `POST /api/subject/hierarchy/set` - update an exercise hierarchy of a subject [[POST_api_subject_hierarchy_set]]

.It can be used by
* all assignees of a subject.

[sidebar]
QUESTION: should we permit all teachers to use this request if a subject's `assignees` equals `null`?
// add if so:
// or all teachers if a subject's `assignees` equals `null`.

.Special status codes

.Request

[source,json]
----
{
  "subject": "fizyka",
  "hierarchy": [
    {
      "name": "mechanika",
      "children": [
        {
          "name": "kinematyka",
          "children": [
            {
              "children": "pociagi-dwa"
            }
          ]
        }
      ]
    }
  ]
}
----

.Response

[source,json]
----
----

.Notes

* none

=== Exercise modification

==== `POST /api/subject/exercise/list` - get all exercises from a subject [[POST_api_subject_exercise_list]]

.It can be used by
* all assignees of a subject,
* or all teachers if a subject's `assignees` equals `null`.

.Special status codes

.Request

[source,json]
----
{
  "subject": "_fizyka"
}
----

.Response

[source,json]
----
{
  "exercises": ["pociagi-dwa", "kula-2"]
}
----

.Notes

* none

==== `POST /api/subject/exercise/add` - create an exercise [[POST_api_subject_exercise_add]]

.It can be used by
* all assignees of a subject,
* or all teachers if a subject's `assignees` equals `null`.

.Special status codes
* `409 Conflict` - the name (`subject` and `exerciseId` properties) is already taken.

.Request

[source,json]
----
{
  "subject": "fizyka",
  "exerciseId": "pociagi-dwa",
  "content": "---\ntype: EqEx\nname: Pociągi dwa 2\n---\nZ miast \\(A\\) i \\(B\\) odległych o d=300km wyruszają jednocześnie\ndwa pociągi z prędkościami v_a=[40;60]km/h oraz v_b=[60;80]km/h.\nW jakiej odległości x=?km od miasta \\(A\\) spotkają się te pociągi?\nPo jakim czasie t=?h się to stanie?\n---\nt=d/(v_a+v_b)\nx=t*v_a\n"
}
----

.Response

[source,json]
----
----

.Notes

// content:ext-dependent
* The `content` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.
// content+:links2static
* The `content` property can contain links to static content.
The User can upload it via the <<PUT_api_subject_static_.subject_.filename>> request.

==== `POST /api/subject/exercise/get` - read a content of an exercise [[POST_api_subject_exercise_get]]

.It can be used by
* all assignees of a subject,
* or all teachers if a subject's `assignees` equals `null`,

.Special status codes
* `200 OK`,
 `403 Forbidden`, `404 Not Found`

.Request

[source,json]
----
{
  "subject": "fizyka",
  "exerciseId": "pociagi-dwa"
}
----

.Response

[source,json]
----
{
  "content": "---\ntype: EqEx\nname: Pociągi dwa 2\n---\nZ miast \\(A\\) i \\(B\\) odległych o d=300km wyruszają jednocześnie\ndwa pociągi z prędkościami v_a=[40;60]km/h oraz v_b=[60;80]km/h.\nW jakiej odległości x=?km od miasta \\(A\\) spotkają się te pociągi?\nPo jakim czasie t=?h się to stanie?\n---\nt=d/(v_a+v_b)\nx=t*v_a\n"
}
----

.Notes

// content:ext-dependent
* The `content` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.

==== `POST /api/subject/exercise/update` - update a content of an exercise [[POST_api_subject_exercise_update]]

.It can be used by
* all assignees of a subject,
* or all teachers if a subject's `assignees` equals `null`.

.Special status codes

.Request

[source,json]
----
{
  "subject": "fizyka",
  "exerciseId": "pociagi-dwa",
  "content": "---\ntype: EqEx\nname: Pociągi dwa 2\n---\nZ miast \\(A\\) i \\(B\\) odległych o d=300km wyruszają jednocześnie\ndwa pociągi z prędkościami v_a=[40;60]km/h oraz v_b=[60;80]km/h.\nW jakiej odległości x=?km od miasta \\(A\\) spotkają się te pociągi?\nPo jakim czasie t=?h się to stanie?\n---\nt=d/(v_a+v_b)\nx=t*v_a\n"
}
----

.Response

[source,json]
----
----

.Notes

// content+:only-changeable
* Only the `content` property is changeable.
Changing an `exerciseId` fails or overwrites an old exercise.
// content:ext-dependent
* The `content` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.

==== `POST /api/subject/exercise/preview` - render an exercise from a content [[POST_api_subject_exercise_preview]]

.It can be used by
* all authorized.

.Special status codes

.Request

[source,json]
----
{
  "content": "---\ntype: EqEx\nname: Pociągi dwa 2\n---\nZ miast \\(A\\) i \\(B\\) odległych o d=300km wyruszają jednocześnie\ndwa pociągi z prędkościami v_a=[40;60]km/h oraz v_b=[60;80]km/h.\nW jakiej odległości x=?km od miasta \\(A\\) spotkają się te pociągi?\nPo jakim czasie t=?h się to stanie?\n---\nt=d/(v_a+v_b)\nx=t*v_a\n",
  "seed": 0
}
----

.Response

[source,json]
----
{
  "type": "EqEx",
  "name": "Pociągi dwa 2",
  "problem": {
    "main": "Z miast \\(A\\) i \\(B\\) odległych o \\(d=300\\;\\mathrm{km}\\) wyruszają jednocześnie\ndwa pociągi z prędkościami \\(v_a= 50\\;\\mathrm{\\frac{km}{h}}\\) oraz \\(v_b=70\\;\\mathrm{\\frac{km}{h}}\\).\nW jakiej odległości \\(x\\) od miasta \\(A\\) spotkają się te pociągi?\nPo jakim czasie \\(t\\) się to stanie?",
    "img": ["1.png", "2.png"],
    "unknown": [
      ["x", "\\mathrm{km}"],
      ["t", "\\mathrm{s}"]
    ]
  },
  "correctAnswer": {
    "answers": [2.5, 125]
  }
}
----

.Notes

// seed+?
* The `seed` property is optional.
// problem-:ext-dependent
* The `problem` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.
// problem-:links2static
* The `problem` property can contain links to static content.
The User can access it via the <<GET_api_subject_static_.subject_.filename>> request.
// content:ext-dependent
* The `content` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.

=== Auth

==== `POST /api/auth/register` - create a new user [[POST_api_auth_register]]

.It can be used by
* anyone who has a valid invitation.

.Special status codes
* `409 Conflict` - the login is already taken.

.Request

[source,json]
----
{
  "login": "user@example.com",
  "name": "User",
  "hashedPassword": "r02H/fnQ3M3Xfjqsr3dg8mY78lBDXWoiR0O0JcXW8VM=",
  "number": 11,
  "invitation": "QwErTy58"
}
----

.Response

[source,json]
----
----

.Notes

// /register:not-authenticate
* This request doesn't authenticate, unlike a <<POST_api_auth_login>> one.
// login+:email!root
* The `login` property is an email address.
With this request, it is not possible to register hard-coded users (like `root`).
// hashedPassword+:def
* The description of the `hashedPassword` property generation is https://github.com/Pikne-Programy/pikne-zadania/issues/22#issuecomment-789536400[here].
// number+:def
* The `number` property is a number or `null`.

==== `POST /api/auth/login` - authenticate [[POST_api_auth_login]]

.It can be used by
* anyone.

.Special status codes

.Request

[source,json]
----
{
  "login": "user@example.com",
  "hashedPassword": "r02H/fnQ3M3Xfjqsr3dg8mY78lBDXWoiR0O0JcXW8VM="
}
----

.Response

[source,json]
----
----

.Notes

// hashedPassword+:def
* The description of the `hashedPassword` property generation is https://github.com/Pikne-Programy/pikne-zadania/issues/22#issuecomment-789536400[here].

==== `POST /api/auth/logout` - unauthenticate [[POST_api_auth_logout]]

.It can be used by
* all authorized.

.Special status codes

.Request

[source,json]
----
----

.Response

[source,json]
----
----

.Notes

* none

=== User

==== `POST /api/user/info` - read user's info [[POST_api_user_info]]

.It can be used by
* all authorized if a request is referring to the User,
* the assignee of the team of the requested user.

.Special status codes

.Request

[source,json]
----
{
  "userId": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
}
----

.Response

[source,json]
----
{
  "name": "User",
  "teamId": 2,
  "number": 11
}
----

.Notes

// userId+?:ommitting=db
* Omitting the `userId` property causes using the User's one.
// number+:def
* The `number` property is a number or `null`.

==== `POST /api/user/update` - update user's info[[POST_api_user_update]]

.It can be used by
* the assignee of the team of the requested user.

.Special status codes

.Request

[source,json]
----
{
  "userId": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "number": 33
}
----

.Response

[source,json]
----
----

.Notes

// #changeable(number,name)
* Only `number` and `name` properties are changeable.
// number+:def
* The `number` property is a number or `null`.

==== `POST /api/user/delete` - delete a user [[POST_api_user_delete]]

.It can be used by
* the assignee of the team of the requested user.

.Special status codes

.Request

[source,json]
----
{
  "userId": "1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755"
}
----

.Response

[source,json]
----
----

.Notes

* none

=== Team

==== `GET /api/team/list` - list all teams [[GET_api_team_list]]

.It can be used by
* all teachers.

.Special status codes

.Request

[source,json]
----
----

.Response

[source,json]
----
[
  {
    "teamId": 1,
    "name": "Teachers",
    "assignee": {
      "userId": "4813494d137e1631bba301d5acab6e7bb7aa74ce1185d456565ef51d737677b2",
      "name": "root"
    },
    "invitation": "QwErTy58"
  },
  {
    "teamId": 2,
    "name": "2d",
    "assignee": {
      "userId": "1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755",
      "name": "Smith"
    },
    "invitation": null
  },
  {
    "teamId": 3,
    "name": "3d",
    "assignee": {
      "userId": "1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755",
      "name": "Smith"
    },
    "invitation": null
  }
]
----

.Notes

// [teams]:admin-id-0
* There is always a hard-coded `admin` team with id `0`.
// invitation-?:if-can-manage
* If the User can manage a team, there is the `invitation` property there.
// invitation-:def
* When a team has closed registration, the `invitation` property is `null`.

==== `POST /api/team/create` - create a team [[POST_api_team_create]]

.It can be used by
* all teachers.

.Special status codes

.Request

[source,json]
----
{
  "name": "2d"
}
----

.Response

[source,json]
----
{
  "teamId": 2
}
----

.Notes

* none

==== `POST /api/team/info` - read team's info [[POST_api_team_info]]

.It can be used by
* all authorized if a request is referring to the User's team,
* all teachers.

.Special status codes

.Request

[source,json]
----
{
  "teamId": 2
}
----

.Response

[source,json]
----
{
  "name": "2d",
  "assignee": {
    "userId": "1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755",
    "name": "Smith"
  },
  "invitation": "QwErTy58",
  "members": [
    {
      "userId": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "name": "User",
      "number": 11
    }
  ]
}
----

.Notes

// invitation&userId-:!student
* The Student will not receive the `invitation` property and any of `userId` properties.
// invitation-:def
* When a team has closed registration, the `invitation` property is `null`.

==== `POST /api/team/update` - update team's info [[POST_api_team_update]]

.It can be used by
* the assignee of the requested team,

.Special status codes
* `409 Conflict` - the invitation is already taken.

.Request

[source,json]
----
{
  "teamId": 2,
  "invitation": "QwErTy58"
}
----

.Response

[source,json]
----
----

.Notes

// assgignee+:only-teacher
* Only a teacher can be an assignee of a team.
// #changeable(invitation,assignee,name)
* Only `invitation`, `assignee` and `name` properties are changeable.
// invitation+:gen-def
* The `invitation` property can also be an empty string `""` (in that case, it will be random)
or `null` (in that case, registration will be closed).

==== `POST /api/team/delete` - delete a team [[POST_api_team_delete]]

.It can be used by
* the assignee of the requested team.

.Special status codes

.Request

[source,json]
----
{
  "teamId": 2
}
----

.Response

[source,json]
----
----

.Notes

* none

////

== Used phrases

.It can be used by
[%collapsible]
====
* anyone,
* all teachers,
* or all teachers if a subject's `assignees` equals `null`,
* anyone if a subject is public and an exercise is listed in a subject's hierarchy,
* all assignees of a subject,
* anyone if a subject is public,
* all authorized,
* all authorized if a request is referring to the User,
* all authorized if a request is referring to the User's team,
* the assignee of the team of the requested user,
* the assignee of the requested team,
* all teachers,
* anyone who has a valid invitation,
====

.Notes
[%collapsible]
====

----
get tags:
(?<=\.Notes\n[^[]*)^// (.*)\n
----

// seed+?
* The `seed` property is optional.

// seed+?:teacher|admin
* Only the Teacher and the Admin can use the `seed` property.
Otherwise, the database provides it.

// content:ext-dependent
* The `content` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.

// description-:ext-dependent
* The `description` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.

// info-:ext-dependent
* The `info` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.

// problem-:ext-dependent
* The `problem` property is dependent on exercise type (ExT).
The one shown above is the EquationExercise (EqEx) one.

// content+:links2static
* The `content` property can contain links to static content.
The User can upload it via the <<PUT_api_subject_static_.subject_.filename>> request.

// problem-:links2static
* The `problem` property can contain links to static content.
The User can access it via the <<GET_api_subject_static_.subject_.filename>> request.

// assignees+:def
* If the `assignees` property equals `null`, all teachers will be able to manage the subject.

// assignees-:def
* If the `assignees` property equals `null`, all teachers can modify the subject.

// done-:def
* The `done` property can be `null` or a number from 0 up to and including 1, see https://github.com/Pikne-Programy/pikne-zadania/issues/24#issuecomment-782939873[#24].

// hashedPassword+:def
* The description of the `hashedPassword` property generation is https://github.com/Pikne-Programy/pikne-zadania/issues/22#issuecomment-789536400[here].

// invitation-:def
* When a team has closed registration, the `invitation` property is `null`.

// number+:def
* The `number` property is a number or `null`.

// [teams]:admin-id-0
* There is always a hard-coded `admin` team with id `0`.

// assignees+:empty-warning
* Only the Admin will be managing the subject if the `assignees` property equals `[]`.

// subject+:underscore-prefix
* Subjects that begins with the `_` character are private and not visible to unauthorized users.

// subject+:unique
* `subject` is a name and an id simultaneously.
It has to be unique.

// assgignee+:only-teacher
* Only a teacher can be an assignee of a team.

// content+:only-changeable
* Only the `content` property is changeable.
Changing an `exerciseId` fails or overwrites an old exercise.

// #changeable(invitation,assignee,name)
* Only `invitation`, `assignee` and `name` properties are changeable.

// #changeable(number,name)
* Only `number` and `name` properties are changeable.

// userId+?:ommitting=db
* Omitting the `userId` property causes using the User's one.

// invitation+:gen-def
* The `invitation` property can also be an empty string `""` (in that case, it will be random)
or `null` (in that case, registration will be closed).

// invitation-?:if-can-manage
* If the User can manage a team, there is the `invitation` property there.

// invitation&userId-:!student
* The Student will not receive the `invitation` property and any of `userId` properties.

// login+:email!root
* The `login` property is an email address.
With this request, it is not possible to register hard-coded users (like `root`).

// /register:not-authenticate
* This request doesn't authenticate, unlike a <<POST_api_auth_login>> one.

// /static-:binary-data
* There should be binary data with an appropriate Content-type in the response.

// /static+:multipart
* The request data should follow the `multipart/form-data` Content-type.

// /hierarchy.subsubject:exs-not-listed
* If the `raw` property equals `false` and the User is authorized, there is a `{"name": "", children: [...]}` (sub-subject) object with all exercises not listed in the hierarchy.

// correctAnswer-:teacher|admin
* Only the Teacher and the Admin receive the `correctAnswer` property.

// description-&done-?:raw=false
* If the `raw` property equals `false`, there is the `description` property and can be the optional `done` property if the User is authenticated.

// subjects-:only-available
* There are only subjects available for the User.

====

////

include::footer.adoc[]
