# Copyright 2021 Marcin Zepp <nircek-2103@protonmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version: "3.9"
services:
  srv:
    build:
      context: frontend
      dockerfile: nginx.dockerfile
    volumes:
      - html:/usr/share/nginx/html
    links:
      - api:backend
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build:
      context: frontend
      dockerfile: angular.dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
      - html:/app/dist
    depends_on:
      - api
  api:
    build:
      context: backend
      dockerfile: denon.dockerfile
    volumes:
      - ./backend:/app
      - ./exercises:/app/exercises
    expose:
      - 8000
    links:
      - db:mongo
    depends_on:
      - db
    user: "deno:${GID}"
  db:
    image: mongo
    ports:
      - 27017:27017
volumes:
  html:
  node_modules:
