version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: denon.dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
