version: "3.9"
services:
  web:
    image: nircek/pikne-zadania
    links:
      - api:backend
    ports:
      - 80:80
    depends_on:
      - api
  api:
    image: nircek/pikne-zadania-frontend
    expose:
      - 8000
    links:
      - db:redis
    depends_on:
      - db
  db:
    image: redis
