# Copyright 2021 Marcin Zepp <nircek-2103@protonmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version: "3.9"
services:
  web:
    build: frontend
    links:
      - api:backend
    ports:
      - 8080:80
    depends_on:
      - api
  api:
    build: backend
    env_file: api.env
    volumes:
      - ./exercises:/app/exercises
    expose:
      - 8000
    links:
      - db:mongo
    depends_on:
      - db
    user: "deno:${GID}"
  db:
    image: mongo
    expose:
      - 27017
