# Copyright 2021 Marcin Zepp <nircek-2103@protonmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version: "3.9"
services:
  web:
    image: nircek/pikne-zadania-frontend
    links:
      - api:backend
    ports:
      - 8080:80
    depends_on:
      - api
    restart: unless-stopped
  api:
    image: nircek/pikne-zadania
    env_file: api.env
    expose:
      - 8000
    links:
      - db:mongo
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data:/data
    restart: unless-stopped
