version: "3.9"
services:
  web:
    build: frontend
    links:
      - api:backend
    ports:
      - 8080:80
    depends_on:
      - api
  api:
    build: backend
    expose:
      - 8000
    links:
      - db:mongo
    depends_on:
      - db
  db:
    image: mongo
    expose:
      - 27017
