name: Node.js

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js 14.15
        uses: actions/setup-node@v2
        with:
          node-version: 14.15

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm build

      - name: Run linter
        run: npm run lint
        if: always()

      - name: Run tests & Generate coverage report
        run: npm test -- --no-watch --code-coverage --browsers FirefoxHeadless
        if: always()

      - uses: codecov/codecov-action@v2
        with:
          files: coverage/lcov.info
        if: always()

  future:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test -- --no-watch --browsers FirefoxHeadless
        if: always()
